dbt_spotify:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: sql-spotify-insights.database.windows.net
      port: 1433
      database: sqldb-spotify-insights
      schema: dbo
      user: stava089
      password: KamyarAli123!

    postgres:
      type: postgres
      host: postgres-dw
      user: admin
      password: admin
      port: 5432
      dbname: spotify
      schema: dbo